# Generated by Django 2.2.6 on 2021-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210422_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeAmount',
            new_name='IngredientAmount',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
