# Generated by Django 2.2.6 on 2021-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210422_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
